### ISSUE TITLE
the number picture is 235,but label failed and number is None

### ISSUE THREAD

**Issue by gitmhg** [IndustryEssentials/ymir#1066]
![image](https://user-images.githubusercontent.com/51695758/185353304-a27a685c-e793-4c10-add5-08291c430d2f.png)

**Comment by phoenix-xhuang** [comment]
Need more info, fill the issue form and logs would be helpful

**Describe the issue**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.
