### ISSUE TITLE
更新最新版本以后，登录报错：找不到该用户，请重试

### ISSUE THREAD

**Issue by wangchao1980** [IndustryEssentials/ymir#1680]
![image](https://user-images.githubusercontent.com/28770548/227605877-307bfcda-a83b-474b-b0ab-652986b01930.png)
更新最新版本以后，登录报错：找不到该用户，请重试

**Comment by phoenix-xhuang** [comment]
更新以后会强制让当前用户的登录状态失效。请重启试下

如果还有问题，请按issue的模版提供相应信息，特别是日志记录

**Describe the issue**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Logs: under ymir-workplace/ymir-data/logs
 - Error Message: in controller/app/hel-log
 - Trace stack

**Additional context**
Add any other context about the problem here.
