### ISSUE TITLE
label free

### ISSUE THREAD

**Issue by hjsybyq** [IndustryEssentials/ymir#1681]
标准平台无法登录，注册失败

**Comment by phoenix-xhuang** [comment]
请按如下格式，提供issue更多信息

**Describe the issue**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Logs: under ymir-workplace/ymir-data/logs
 - Error Message: in controller/app/hel-log
 - Trace stack

**Additional context**
Add any other context about the problem here.
