### ISSUE TITLE
Unable to terminate labeling task and fetch result dataset

### ISSUE THREAD

**Issue by kk52099** [IndustryEssentials/ymir#336]
![image](https://user-images.githubusercontent.com/18585577/156147663-437de454-44d7-4a08-b8b0-92d615eebb3f.png)
点“终止”，没有任何效果

**Comment by phoenix-xhuang** [comment]
can you provide more context? e.g. controller.log errors under ymir-workplace/ymir-data/logs at your deploy environment.

**Comment by phoenix-xhuang** [comment]
Here is a template to describe your issue

**Describe the issue**
A clear and concise description of what the bug is.
**To Reproduce**
Steps to reproduce the behavior:
1. Go to ‘...’
2. Click on ‘....’
3. Scroll down to ‘....’
4. See error
**Expected behavior**
A clear and concise description of what you expected to happen.
**Screenshots**
If applicable, add screenshots to help explain your problem.
**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]
**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]
**Additional context**
Add any other context about the problem here.
