### ISSUE TITLE
Model Verification:docker images only had sample_image

### ISSUE THREAD

**Issue by Sn34931** [IndustryEssentials/ymir#711]
**Describe the issue**
Model Verification：docker images only had sample_image

**To Reproduce**
when I finished training the model(used yolov4) and wanted to verify it, the docker images only had samples

**Screenshots**
![111](https://user-images.githubusercontent.com/101860899/171308114-07c31309-4183-44b8-b2f2-283970273308.png)
![111](https://user-images.githubusercontent.com/101860899/171308520-93428199-3a85-4bb7-abb4-e83fb95c7337.png)

**Env**
 - OS: ubuntu:18.04
 - Ymir Version [ release-1.0.0]
 - Docker version 20.10.16, build aa7e414
 - Docker Compose version v2.5.1
 -
**Additional context**

**Comment by Zhang-SJ930104** [comment]
Because the type of image will be matched according to the task type.
If you want to perform mining, infer and model validation, you need to copy a mining image from the public image.
![image](https://user-images.githubusercontent.com/91466580/171313673-84f831f6-abeb-4e27-9855-971564964e2b.png)
Thank you for your feedback!

**Comment by Sn34931** [comment]
> Because the type of image will be matched according to the task type. If you want to perform mining, infer and model validation, you need to copy a mining image from the public image. ![image](https://user-images.githubusercontent.com/91466580/171313673-84f831f6-abeb-4e27-9855-971564964e2b.png) Thank you for your feedback!

thanks
